#!/usr/bin/env python3
"""Regenerate the FAQPage JSON-LD from the rendered FAQ accordion.

The design system requires the schema answers to match the rendered copy exactly.
Hand-maintaining two copies guarantees they drift, so this derives one from the
other. Run it after any FAQ copy edit, including after filling {{CONFIRM: }}
tokens:

    python3 tools/build-faq-schema.py [page.html ...]

Defaults to index.html. Rewrites the block between the FAQ-SCHEMA markers.
"""
import html
import json
import re
import sys

ROW = re.compile(
    r'<button class="hx-faq-q"[^>]*>\s*<span>(?P<q>.*?)</span>.*?'
    r'<div class="hx-faq-a">\s*<div>\s*(?P<a>.*?)\s*</div>\s*</div>',
    re.S,
)
START = "<!-- FAQ-SCHEMA:START (generated by tools/build-faq-schema.py, do not hand-edit) -->"
END = "<!-- FAQ-SCHEMA:END -->"


def text_of(fragment: str) -> str:
    """Strip tags, unescape entities, collapse whitespace."""
    plain = re.sub(r"<[^>]+>", " ", fragment)
    return re.sub(r"\s+", " ", html.unescape(plain)).strip()


def build(path: str) -> int:
    src = open(path, encoding="utf-8").read()
    if START not in src or END not in src:
        print(f"{path}: no FAQ-SCHEMA markers, skipped")
        return 0

    entities = [
        {
            "@type": "Question",
            "name": text_of(m.group("q")),
            "acceptedAnswer": {"@type": "Answer", "text": text_of(m.group("a"))},
        }
        for m in ROW.finditer(src)
    ]
    if not entities:
        print(f"{path}: no FAQ rows found, schema left alone")
        return 0

    payload = json.dumps(
        {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": entities},
        indent=2,
        ensure_ascii=False,
    )
    block = (
        f'{START}\n<script type="application/ld+json">\n{payload}\n</script>\n{END}'
    )
    head, _, rest = src.partition(START)
    _, _, tail = rest.partition(END)
    open(path, "w", encoding="utf-8").write(head + block + tail)

    unresolved = sum(1 for e in entities if "{{CONFIRM" in json.dumps(e))
    print(f"{path}: {len(entities)} questions written, {unresolved} still carry a CONFIRM token")
    return len(entities)


if __name__ == "__main__":
    for target in sys.argv[1:] or ["index.html"]:
        build(target)
